name: Build Lua Json
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
           
      - name: Generate Origin file list with python
        run: 
          echo "hello" > test.file
      
      - uses: EndBug/add-and-commit@v9
        with:
          message: Generate Origin file list
          committer_name: GitHub Actions
          committer_email: actions@github.com
